import {
    Activity,
    BarChart3,
    BookOpen,
    Briefcase,
    Calendar,
    CircleHelp,
    ClipboardList,
    Cloud,
    Code2,
    Columns3,
    CreditCard,
    FileText,
    Folder,
    Globe,
    HeartPulse,
    Image,
    LifeBuoy,
    Link2,
    List,
    ListOrdered,
    Lock,
    Mail,
    Map,
    MessageSquare,
    Music,
    Receipt,
    Rocket,
    Settings,
    ShoppingBag,
    Sparkles,
    SquareCheck,
    SquarePen,
    Store,
    Tag,
    Ticket,
    Timer,
    UtensilsCrossed,
    Users,
    Wallet,
} from 'lucide-react'

/** Lucide icons for Lab seed suggestion chips. */
const ICONS = {
    quiz: CircleHelp,
    mail: Mail,
    rocket: Rocket,
    briefcase: Briefcase,
    sparkles: Sparkles,
    chart: BarChart3,
    columns: Columns3,
    tag: Tag,
    book: BookOpen,
    file: FileText,
    bag: ShoppingBag,
    card: CreditCard,
    calendar: Calendar,
    chat: MessageSquare,
    music: Music,
    check: SquareCheck,
    receipt: Receipt,
    users: Users,
    settings: Settings,
    steps: ListOrdered,
    lock: Lock,
    cloud: Cloud,
    utensils: UtensilsCrossed,
    activity: Activity,
    globe: Globe,
    ticket: Ticket,
    image: Image,
    edit: SquarePen,
    timer: Timer,
    bar: BarChart3,
    link: Link2,
    list: List,
    pulse: HeartPulse,
    folder: Folder,
    map: Map,
    form: ClipboardList,
    wallet: Wallet,
    life: LifeBuoy,
    code: Code2,
    store: Store,
}

export function SeedIcon({ name = 'sparkles', className = 'h-3.5 w-3.5' }) {
    const Icon = ICONS[name] || Sparkles

    return <Icon className={className} strokeWidth={1.75} aria-hidden="true" />
}
