export const MAX_ATTACHMENTS = 8
export const MAX_FILE_BYTES = 10 * 1024 * 1024

export const COMPOSER_ACCEPT = [
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/gif',
    'image/svg+xml',
    '.php',
    '.js',
    '.jsx',
    '.mjs',
    '.cjs',
    '.ts',
    '.tsx',
    '.css',
    '.scss',
    '.html',
    '.json',
    '.md',
    '.txt',
    '.pdf',
    '.csv',
    '.xml',
    '.yml',
    '.yaml',
    '.vue',
    '.py',
    '.rb',
    '.go',
    '.rs',
    '.java',
    '.zip',
    'application/pdf',
    'application/json',
    'text/plain',
    'text/javascript',
    'text/css',
    'text/html',
    'text/markdown',
    'text/csv',
    'application/zip',
].join(',')
